-- MySQL Script generated by MySQL Workbench
-- 09/13/15 12:14:27
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`departamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`departamento` (
  `cod_dep` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_dep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `matricula` VARCHAR(20) NOT NULL,
  `salario` INT NULL,
  `cargo` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `comissa` DECIMAL NULL,
  `cod_dep` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  CONSTRAINT `fk_funcionario_departamento1`
    FOREIGN KEY (`cod_dep`)
    REFERENCES `mydb`.`departamento` (`cod_dep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_funcionario_departamento1_idx` ON `mydb`.`funcionario` (`cod_dep` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`bonus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bonus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bonus` (
  `matricula` VARCHAR(20) NOT NULL,
  `bonus` INT NULL,
  PRIMARY KEY (`matricula`),
  CONSTRAINT `fk_bonus_funcionario`
    FOREIGN KEY (`matricula`)
    REFERENCES `mydb`.`funcionario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_bonus_funcionario_idx` ON `mydb`.`bonus` (`matricula` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
